version: "3.8"

services:
  app:
    image: cncjs/cncjs:v1.11.3
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --config
      - /var/lib/cncjs/.cncrc
    volumes:
      - cncjs-data:/var/lib/cncjs
    networks:
      - infra_reverse-proxy
    deploy:
      replicas: 1
      update_config:
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          memory: 512M

volumes:
  cncjs-data:

networks:
  infra_reverse-proxy:
    external: true
